// Provenance tracking: mark findings as observation or recommendation.
// Observation = detected in code; Recommendation = generated by LLM.

export type FindingSource = "daemon-scan" | "manual" | "batch" | "llm-recommendation";
export type FindingProvenance = "observation" | "recommendation";

/**
 * Categorize finding source as observation or recommendation.
 */
export function provenanceOf(source: FindingSource): FindingProvenance {
  if (source === "llm-recommendation") return "recommendation";
  return "observation";
}

export interface ProvenanceTag {
  /** "observation" | "recommendation" */
  provenance: FindingProvenance;
  /** Original source */
  source: FindingSource;
  /** Confidence: 0-1 for recommendations, always 1 for observations */
  confidence: number;
  /** Audit trail: who/how the finding was sourced */
  trail: string;
}

/**
 * Create provenance tag from finding metadata.
 */
export function tagProvenance(opts: {
  source: FindingSource;
  confidence?: number;
  trail?: string;
}): ProvenanceTag {
  const { source, confidence = 1, trail = "" } = opts;

  if (source === "llm-recommendation") {
    return {
      provenance: "recommendation",
      source,
      confidence: Math.min(1, Math.max(0, confidence)),
      trail: trail || "LLM-generated",
    };
  }

  return {
    provenance: "observation",
    source,
    confidence: 1,
    trail: trail || source,
  };
}

/**
 * Filter findings: keep only observations or recommendations.
 */
export function filterByProvenance(
  findings: Array<{ source: FindingSource }>,
  provenance: FindingProvenance,
): Array<{ source: FindingSource }> {
  return findings.filter((f) => provenanceOf(f.source) === provenance);
}

/**
 * Separate observations and recommendations.
 */
export function separateProvenance(findings: Array<{ source: FindingSource }>) {
  return {
    observations: filterByProvenance(findings, "observation"),
    recommendations: filterByProvenance(findings, "recommendation"),
  };
}

/**
 * Provenance stats: observation vs recommendation counts.
 */
export function provenanceStats(
  findings: Array<{ source: FindingSource }>,
): {
  total: number;
  observations: number;
  recommendations: number;
  recommendationRatio: number;
} {
  const observations = filterByProvenance(findings, "observation").length;
  const recommendations = filterByProvenance(findings, "recommendation").length;
  return {
    total: findings.length,
    observations,
    recommendations,
    recommendationRatio: findings.length > 0 ? recommendations / findings.length : 0,
  };
}
