"use client";

import { useMemo, useState } from "react";
import { useSession } from "../session/SessionContext";
import type { FindingStatus } from "@/lib/schema";
import { CARD_CLASS, CARD_INSET_CLASS, LABEL_CLASS, PRIMARY_BUTTON_CLASS, SECTION_KICKER_CLASS, TEXTAREA_CLASS } from "./styles";

const STATUS_LABELS: Record<FindingStatus, string> = {
  implemented: "Implemented",
  partially_implemented: "Partially implemented",
  documented_only: "Documented only",
  contradicted: "Contradicted",
  unclear: "Unclear",
  out_of_scope: "Out of scope",
};

const STATUS_CLASSES: Record<FindingStatus, string> = {
  implemented: "text-tertiary border-tertiary/30 bg-tertiary/10",
  partially_implemented: "text-secondary border-secondary/30 bg-secondary/10",
  documented_only: "text-on-surface-variant/70 border-outline-variant/30 bg-surface-container-highest/20",
  contradicted: "text-primary border-primary/30 bg-primary/10",
  unclear: "text-on-surface-variant/50 border-outline-variant/20 bg-transparent",
  out_of_scope: "text-on-surface-variant/50 border-outline-variant/20 bg-transparent",
};

export function ContractMapScreen() {
  const { contractMap, selectedFindingIds, toggleFinding, objective, setObjective, buildHandoff } = useSession();
  const [filter, setFilter] = useState<FindingStatus | "all">("all");

  const filtered = useMemo(() => {
    const findings = contractMap?.findings ?? [];
    return filter === "all" ? findings : findings.filter((f) => f.status === filter);
  }, [contractMap, filter]);

  if (!contractMap) {
    return (
      <section className={CARD_CLASS}>
        <p className="font-body-md text-on-surface-variant italic">No contract map has been generated yet.</p>
      </section>
    );
  }

  return (
    <section className={CARD_CLASS}>
      <div className="flex items-center gap-2 mb-2">
        <span className={SECTION_KICKER_CLASS}>§ 3</span>
        <div className="h-px w-8 bg-primary/30" />
      </div>
      <h2 className="font-document-heading text-2xl text-on-surface mb-1">Model Analysis</h2>
      <p className="font-body-md text-on-surface-variant text-sm italic mt-0 mb-6">
        Generated by <span className="font-technical-data not-italic">{contractMap.modelId}</span>. Select findings to carry into the refinery.
      </p>

      <div className="overflow-x-auto -mx-1 px-1">
        <div className="flex gap-2 min-w-max pb-1">
          <FilterPill label="All" active={filter === "all"} onClick={() => setFilter("all")} />
          {(Object.keys(STATUS_LABELS) as FindingStatus[]).map((s) => (
            <FilterPill key={s} label={STATUS_LABELS[s]} active={filter === s} onClick={() => setFilter(s)} />
          ))}
        </div>
      </div>

      <div className="grid gap-3 mt-4">
        {filtered.length === 0 && <p className="font-body-md text-on-surface-variant/50">No findings match this filter.</p>}
        {filtered.map((f) => {
          const selected = selectedFindingIds.has(f.id);
          return (
            <label
              key={f.id}
              className={`flex gap-3 items-start p-4 rounded-lg cursor-pointer transition-all border ${
                selected
                  ? "bg-primary-container/10 border-primary-container/50"
                  : "bg-surface-container border-outline-variant/10 hover:border-outline-variant/30"
              }`}
            >
              <input
                type="checkbox"
                checked={selected}
                onChange={() => toggleFinding(f.id)}
                className="mt-1 w-4 h-4 shrink-0 accent-primary-container cursor-pointer"
              />
              <div className="min-w-0 flex-1">
                <div className="flex justify-between gap-2 flex-wrap">
                  <span className="font-ui-label font-semibold text-sm text-on-surface">{f.claim}</span>
                  <span className={`px-2 py-0.5 rounded-full font-technical-data text-[10px] uppercase tracking-wide border ${STATUS_CLASSES[f.status]}`}>
                    {STATUS_LABELS[f.status]}
                  </span>
                </div>
                <p className="font-body-md text-[13px] text-on-surface-variant my-1.5">{f.explanation}</p>
                <div className="font-technical-data text-[11px] text-on-surface-variant/40">
                  Confidence {f.confidence.toFixed(2)}
                  {f.missingProof ? ` · Missing proof: ${f.missingProof}` : ""}
                </div>
                <div className="flex gap-1.5 flex-wrap mt-2">
                  {f.evidenceFor.map((e, i) => (
                    <span key={`for-${i}`} className="px-2 py-0.5 rounded-full font-technical-data text-[10px] uppercase border border-tertiary/30 text-tertiary bg-tertiary/10">
                      + {e.source}
                    </span>
                  ))}
                  {f.evidenceAgainst.map((e, i) => (
                    <span key={`against-${i}`} className="px-2 py-0.5 rounded-full font-technical-data text-[10px] uppercase border border-primary/30 text-primary bg-primary/10">
                      − {e.source}
                    </span>
                  ))}
                </div>
              </div>
            </label>
          );
        })}
      </div>

      <div className={`${CARD_INSET_CLASS} mt-5`}>
        <label className="block">
          <span className={LABEL_CLASS}>Desired outcome (becomes the handoff objective)</span>
          <textarea
            rows={3}
            value={objective}
            onChange={(e) => setObjective(e.target.value)}
            placeholder="What should the next agent run accomplish?"
            className={TEXTAREA_CLASS}
          />
        </label>
        <div className="mt-3">
          <button
            type="button"
            disabled={selectedFindingIds.size === 0 && !objective.trim()}
            onClick={buildHandoff}
            className={PRIMARY_BUTTON_CLASS}
          >
            Send to refinery ({selectedFindingIds.size} selected) →
          </button>
        </div>
      </div>
    </section>
  );
}

function FilterPill({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`font-technical-data text-[11px] uppercase tracking-wide px-3 py-2 rounded-full border whitespace-nowrap transition-all ${
        active
          ? "border-primary-container bg-primary-container/15 text-primary"
          : "border-outline-variant/20 bg-surface-container text-on-surface-variant/60 hover:border-outline-variant/40"
      }`}
    >
      {label}
    </button>
  );
}
