"use client";

import { useMemo, useState } from "react";
import { useSession } from "../session/SessionContext";
import type { FindingStatus } from "@/lib/schema";

const STATUS_LABELS: Record<FindingStatus, string> = {
  implemented: "Implemented",
  partially_implemented: "Partially implemented",
  documented_only: "Documented only",
  contradicted: "Contradicted",
  unclear: "Unclear",
  out_of_scope: "Out of scope",
};

const STATUS_COLORS: Record<FindingStatus, string> = {
  implemented: "var(--ok)",
  partially_implemented: "var(--brass-l)",
  documented_only: "var(--hyp)",
  contradicted: "var(--zinnober)",
  unclear: "var(--mut)",
  out_of_scope: "var(--mut)",
};

export function ContractMapScreen() {
  const { contractMap, selectedFindingIds, toggleFinding, objective, setObjective, buildHandoff } = useSession();
  const [filter, setFilter] = useState<FindingStatus | "all">("all");

  const filtered = useMemo(() => {
    const findings = contractMap?.findings ?? [];
    return filter === "all" ? findings : findings.filter((f) => f.status === filter);
  }, [contractMap, filter]);

  if (!contractMap) {
    return (
      <section className="card" style={{ padding: 20 }}>
        <p className="serif">No contract map has been generated yet.</p>
      </section>
    );
  }

  return (
    <section className="card" style={{ padding: 20 }}>
      <h2 style={{ fontSize: 20, margin: "0 0 4px" }}>§ 3 · Contract map</h2>
      <p className="serif" style={{ color: "var(--paper-dim)", marginTop: 0, fontSize: 14 }}>
        Generated by <span className="mono">{contractMap.modelId}</span>. Select findings to carry into the handoff.
      </p>

      <div className="scroll-x" style={{ marginTop: 12 }}>
        <div style={{ display: "flex", gap: 6, minWidth: "max-content" }}>
          <FilterPill label="All" active={filter === "all"} onClick={() => setFilter("all")} />
          {(Object.keys(STATUS_LABELS) as FindingStatus[]).map((s) => (
            <FilterPill key={s} label={STATUS_LABELS[s]} active={filter === s} onClick={() => setFilter(s)} />
          ))}
        </div>
      </div>

      <div style={{ display: "grid", gap: 10, marginTop: 14 }}>
        {filtered.length === 0 && <p className="serif" style={{ color: "var(--mut)" }}>No findings match this filter.</p>}
        {filtered.map((f) => {
          const selected = selectedFindingIds.has(f.id);
          return (
            <label
              key={f.id}
              className="card-inset"
              style={{ padding: 12, display: "flex", gap: 10, alignItems: "flex-start", cursor: "pointer", borderColor: selected ? "var(--brass-d)" : undefined }}
            >
              <input type="checkbox" checked={selected} onChange={() => toggleFinding(f.id)} style={{ marginTop: 3, width: 18, height: 18, flex: "0 0 auto" }} />
              <div style={{ minWidth: 0, flex: 1 }}>
                <div style={{ display: "flex", justifyContent: "space-between", gap: 8, flexWrap: "wrap" }}>
                  <span style={{ fontWeight: 600, fontSize: 14 }}>{f.claim}</span>
                  <span className="pill">
                    <span className="dot" style={{ background: STATUS_COLORS[f.status] }} />
                    {STATUS_LABELS[f.status]}
                  </span>
                </div>
                <p className="serif" style={{ fontSize: 13, margin: "6px 0" }}>{f.explanation}</p>
                <div className="mono" style={{ fontSize: 11, color: "var(--mut)" }}>
                  Confidence {f.confidence.toFixed(2)}
                  {f.missingProof ? ` · Missing proof: ${f.missingProof}` : ""}
                </div>
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 6 }}>
                  {f.evidenceFor.map((e, i) => (
                    <span key={`for-${i}`} className="pill" style={{ borderColor: "#2a3a22", color: "var(--ok)" }}>
                      + {e.source}
                    </span>
                  ))}
                  {f.evidenceAgainst.map((e, i) => (
                    <span key={`against-${i}`} className="pill" style={{ borderColor: "var(--bordeaux-d)", color: "#e7a9b6" }}>
                      − {e.source}
                    </span>
                  ))}
                </div>
              </div>
            </label>
          );
        })}
      </div>

      <div className="card-inset" style={{ padding: 14, marginTop: 18 }}>
        <label style={{ display: "block" }}>
          <span className="mono" style={{ display: "block", fontSize: 10, letterSpacing: "0.05em", textTransform: "uppercase", color: "var(--mut)", marginBottom: 5 }}>
            Desired outcome (becomes the handoff objective)
          </span>
          <textarea rows={3} value={objective} onChange={(e) => setObjective(e.target.value)} placeholder="What should the next agent run accomplish?" />
        </label>
        <div style={{ marginTop: 10 }}>
          <button className="primary" type="button" disabled={selectedFindingIds.size === 0 && !objective.trim()} onClick={buildHandoff}>
            Generate handoff ({selectedFindingIds.size} selected) →
          </button>
        </div>
      </div>
    </section>
  );
}

function FilterPill({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="mono"
      style={{
        fontSize: 11,
        padding: "7px 11px",
        borderRadius: 999,
        border: `1px solid ${active ? "var(--brass)" : "var(--line)"}`,
        background: active ? "rgba(183,138,62,.12)" : "var(--ink2)",
        color: active ? "var(--brass-l)" : "var(--mut)",
        minHeight: 36,
      }}
    >
      {label}
    </button>
  );
}
