import type { SessionExport } from "./schema";

export function sessionToJson(session: SessionExport): string {
  return JSON.stringify(session, null, 2);
}

function evList(items: { source: string }[]): string {
  return items.length ? items.map((e) => `\`${e.source}\``).join(", ") : "(none)";
}

export function sessionToMarkdown(session: SessionExport): string {
  const lines: string[] = [];
  lines.push(`# ALFRED session export — ${session.repo.owner}/${session.repo.name}@${session.repo.ref}`);
  lines.push("");
  lines.push(`Exported: ${session.exportedAt}`);
  lines.push(`Repository: ${session.repo.url}`);
  if (session.modelsUsed.length) {
    lines.push(`Models used: ${session.modelsUsed.map((m) => `${m.purpose}=${m.modelId}`).join(", ")}`);
  }
  lines.push("");

  if (session.warnings.length) {
    lines.push("## Warnings");
    for (const w of session.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  if (session.inventory) {
    const inv = session.inventory;
    lines.push("## Repository inventory");
    lines.push(`- Default branch: ${inv.identity.defaultBranch}`);
    lines.push(`- Description: ${inv.identity.description ?? "(none)"}`);
    lines.push(`- Tree: ${inv.tree.status}${inv.tree.status === "loaded" ? ` (${inv.tree.data.length} entries)` : ""}`);
    lines.push(`- Docs: ${inv.docs.status}${inv.docs.status === "loaded" ? ` (${inv.docs.data.map((d) => d.path).join(", ")})` : ""}`);
    lines.push(`- package.json: ${inv.packageManifest.status}`);
    lines.push(`- Commits: ${inv.commits.status}`);
    lines.push(`- Pull requests: ${inv.pullRequests.status}`);
    lines.push(`- Issues: ${inv.issues.status}`);
    if (inv.warnings.length) lines.push(`- Inventory warnings: ${inv.warnings.join("; ")}`);
    lines.push("");
  }

  if (session.contractMap) {
    lines.push("## Contract map");
    lines.push(`Generated by: ${session.contractMap.modelId} at ${session.contractMap.generatedAt}`);
    lines.push("");
    lines.push("| Claim | Status | Confidence | Evidence for | Evidence against |");
    lines.push("|---|---|---|---|---|");
    for (const f of session.contractMap.findings) {
      lines.push(
        `| ${f.claim} | ${f.status} | ${f.confidence.toFixed(2)} | ${evList(f.evidenceFor)} | ${evList(f.evidenceAgainst)} |`,
      );
    }
    lines.push("");
  }

  if (session.handoff) {
    const h = session.handoff;
    lines.push("## Agent handoff");
    lines.push(`**Objective:** ${h.objective}`);
    lines.push("");
    lines.push("**Current verified state:**");
    lines.push(h.currentVerifiedState);
    lines.push("");
    lines.push("**Non-goals:**");
    for (const n of h.nonGoals) lines.push(`- ${n}`);
    lines.push("");
    lines.push("**Acceptance criteria:**");
    for (const c of h.acceptanceCriteria) lines.push(`- [${c.id}] ${c.text}`);
    lines.push("");
    lines.push("**Stop conditions:**");
    for (const s of h.stopConditions) lines.push(`- ${s}`);
    lines.push("");
  }

  if (session.acceptanceReport) {
    const ar = session.acceptanceReport;
    lines.push("## Acceptance report");
    lines.push(ar.summary);
    lines.push("");
    lines.push("| Criterion | Verdict | Evidence | Note |");
    lines.push("|---|---|---|---|");
    for (const c of ar.criteria) {
      lines.push(`| ${c.criterionText} | ${c.verdict} | ${evList(c.evidence)} | ${c.note} |`);
    }
    if (ar.unsupportedClaims.length) {
      lines.push("");
      lines.push("**Unsupported agent claims:**");
      for (const u of ar.unsupportedClaims) lines.push(`- ${u}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
